version: "2.4"

services:
  leanote:
    build:
      context: ./leanote
      dockerfile: Dockerfile
    command: 'bash ./bin/run.sh'
    ports:
      - 9000:9000
    depends_on:
      - mongo
    volumes:
      - ./leanote/app.conf:/root/conf/app.conf

  mongo:
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017
    volumes:
      - ./mongo/db_data:/data/db
      - ./leanote/leanote/mongodb_backup/leanote_install_data/:/tmp/leanote_seed_data
