version: "2.4"

services:
  leanote:
    build:
      context: ./leanote
      dockerfile: Dockerfile
    command: 'bash ./bin/run.sh'
    depends_on:
      - mongo
    volumes:
      - ./leanote/app.conf:/root/conf/app.conf:ro

  mongo:
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017
    volumes:
      - ./mongo/db_data:/data/db
      - ./leanote/leanote/mongodb_backup/leanote_install_data/:/tmp/leanote_seed_data:ro

  nginx:
    image: nginx:1.21.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - leanote
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
